import Head from "next/head";
import Header from "./components/Header";

function Home() {
  <div>
    <Head>
      <title>Next.js</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Header />

    <main>
      <h1>Início</h1>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis omnis officia cupiditate hic repellat veritatis consectetur necessitatibus? Rerum at veritatis vel soluta, minus tempore deserunt ullam impedit architecto voluptas, dolore id! Nemo illum doloremque ex possimus amet fuga suscipit accusamus.</p>
    </main>

  </div>
}

export default Home;